# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('categoryID', models.IntegerField()),
                ('publishing', models.CharField(max_length=128)),
                ('dateIN', models.DateField()),
                ('quantityIN', models.IntegerField()),
                ('quantityOUT', models.IntegerField()),
                ('quantityLOSS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBorrow', models.DateField()),
                ('dateReturn', models.DateField()),
                ('isloss', models.BooleanField(default=0)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookid', to='Bookmis.Book')),
            ],
        ),
        migrations.CreateModel(
            name='LossReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lossDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('level', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
                ('maxbooknum', models.IntegerField()),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('readerID', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('perssion', models.IntegerField(default=1)),
                ('sex', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=12)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookmis.MemberLevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lossreport',
            name='readerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookmis.MyUser'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='readerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='Bookmis.MyUser'),
        ),
    ]
