# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0002_auto_20171205_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='isReturn',
            field=models.BooleanField(default=0),
        ),
    ]
