# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0003_borrow_isreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='level',
            field=models.ForeignKey(default='普通会员', on_delete=django.db.models.deletion.CASCADE, to='Bookmis.MemberLevel'),
        ),
    ]
