# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0004_auto_20171205_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantityLOSS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantityOUT',
            field=models.IntegerField(default=0),
        ),
    ]
