# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0005_auto_20171205_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dateIN',
            field=models.DateField(auto_now=True),
        ),
    ]
