# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0006_auto_20171207_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='perssion',
            new_name='permission',
        ),
    ]
