# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0007_auto_20171207_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categoryID',
            field=models.IntegerField(),
        ),
    ]
