# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0010_auto_20171207_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='booknum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memberlevel',
            name='days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='memberlevel',
            name='fee',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='memberlevel',
            name='maxbooknum',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='level',
            field=models.ForeignKey(default='普通会员', on_delete=django.db.models.deletion.CASCADE, related_name='ulevel', to='Bookmis.MemberLevel'),
        ),
    ]
