# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0011_auto_20171207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dateIN',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='dateBorrow',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lossreport',
            name='lossDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
