# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0014_myuser_booknum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='booknum',
            new_name='book_num',
        ),
    ]
