# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0015_auto_20171207_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlevel',
            name='maxbooknum',
            field=models.IntegerField(default=3),
        ),
    ]
