# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0017_auto_20171208_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='isReturn',
            field=models.CharField(default='否', max_length=3),
        ),
    ]
