# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0018_auto_20171209_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='bookID',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='readerID',
            new_name='reader',
        ),
    ]
