# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0020_auto_20171209_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lossreport',
            old_name='readerID',
            new_name='reader',
        ),
    ]
