# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmis', '0021_auto_20171209_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isloss',
            field=models.CharField(default='否', max_length=3),
        ),
    ]
